In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as py
import seaborn as sns

In [95]:
df = pd.read_csv('./penguins_size.csv')

In [96]:
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
3  Adelie  Torgersen               NaN              NaN                NaN   
4  Adelie  Torgersen              36.7             19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [97]:
df['sex'].describe()

count      334
unique       3
top       MALE
freq       168
Name: sex, dtype: object

In [98]:
print(df['species'].unique())
print(df['island'].unique())
print(df['sex'].unique())

['Adelie' 'Chinstrap' 'Gentoo']
['Torgersen' 'Biscoe' 'Dream']
['MALE' 'FEMALE' nan '.']


In [99]:
df['sex'].fillna(df['sex'].mode()[0],inplace=True)

In [100]:
temp1 = pd.get_dummies(df['species'],dtype='int64',drop_first=True)
temp2 = pd.get_dummies(df['island'],dtype='int64',drop_first=True)

In [101]:
df = pd.concat([df,temp1,temp2],axis=1)

In [102]:
df.drop(['species','island'],axis=1,inplace=True)

In [103]:
from sklearn.preprocessing import StandardScaler

In [104]:
scaler = StandardScaler()

In [105]:
def sex(name):
    if name == 'MALE':
        return 1
    else: 
        return 0

In [106]:
df['sex'] = df['sex'].apply(sex)

In [107]:
df.head()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g  sex  \
0              39.1             18.7              181.0       3750.0    1   
1              39.5             17.4              186.0       3800.0    0   
2              40.3             18.0              195.0       3250.0    0   
3               NaN              NaN                NaN          NaN    1   
4              36.7             19.3              193.0       3450.0    0   

   Chinstrap  Gentoo  Dream  Torgersen  
0          0       0      0          1  
1          0       0      0          1  
2          0       0      0          1  
3          0       0      0          1  
4          0       0      0          1

In [108]:
df.isna().sum()

culmen_length_mm     2
culmen_depth_mm      2
flipper_length_mm    2
body_mass_g          2
sex                  0
Chinstrap            0
Gentoo               0
Dream                0
Torgersen            0
dtype: int64

In [109]:
df['culmen_length_mm'].fillna(df['culmen_length_mm'].mean(),inplace=True)
df['culmen_depth_mm'].fillna(df['culmen_depth_mm'].mean(),inplace=True)
df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean(),inplace=True)
df['body_mass_g'].fillna(df['body_mass_g'].mean(),inplace=True)

In [110]:
df.head()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g  sex  \
0          39.10000         18.70000         181.000000  3750.000000    1   
1          39.50000         17.40000         186.000000  3800.000000    0   
2          40.30000         18.00000         195.000000  3250.000000    0   
3          43.92193         17.15117         200.915205  4201.754386    1   
4          36.70000         19.30000         193.000000  3450.000000    0   

   Chinstrap  Gentoo  Dream  Torgersen  
0          0       0      0          1  
1          0       0      0          1  
2          0       0      0          1  
3          0       0      0          1  
4          0       0      0          1

In [111]:
df.isna().sum()

culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
Chinstrap            0
Gentoo               0
Dream                0
Torgersen            0
dtype: int64

    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x_scaled = scaler.fit_transform(x)

In [131]:
x = df.drop('sex',axis=1)
y = df['sex']

In [132]:
x_scaled = scaler.fit_transform(x)

In [116]:
from sklearn.model_selection import train_test_split

In [153]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [154]:
dt = DecisionTreeClassifier()
nb = GaussianNB()
knn = KNeighborsClassifier()
lg = LogisticRegression()

In [141]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled,y, test_size=0.2, random_state=42)

In [157]:
dt.fit(x_train,y_train)
nb.fit(x_train,y_train)
knn.fit(x_train,y_train)
lg.fit(x_train,y_train)

LogisticRegression()

In [158]:
y_dt = dt.predict(x_test)
y_nb = nb.predict(x_test)
y_knn = knn.predict(x_test)
y_lg = lg.predict(x_test)

In [159]:
pd.DataFrame({'Prediction':y_dt,'Actual':y_test})

Prediction  Actual
194           1       1
157           0       0
225           0       0
208           0       0
318           0       0
..          ...     ...
321           1       1
172           0       0
73            1       1
76            0       0
16            1       0

[69 rows x 2 columns]

In [160]:
pd.DataFrame({'Prediction':y_nb,'Actual':y_test})

Prediction  Actual
194           1       1
157           0       0
225           0       0
208           0       0
318           0       0
..          ...     ...
321           1       1
172           0       0
73            1       1
76            0       0
16            0       0

[69 rows x 2 columns]

In [161]:
pd.DataFrame({'Prediction':y_knn,'Actual':y_test})

Prediction  Actual
194           1       1
157           0       0
225           0       0
208           0       0
318           0       0
..          ...     ...
321           1       1
172           0       0
73            1       1
76            0       0
16            0       0

[69 rows x 2 columns]

In [162]:
pd.DataFrame({'Prediction':y_lg,'Actual':y_test})

Prediction  Actual
194           1       1
157           0       0
225           0       0
208           0       0
318           0       0
..          ...     ...
321           1       1
172           0       0
73            1       1
76            0       0
16            1       0

[69 rows x 2 columns]

In [163]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [178]:
print('Accuracy Decision Tree',accuracy_score(y_pred=y_dt,y_true=y_test))
print('Classificaition Decision Tree\n',classification_report(y_pred=y_dt,y_true=y_test))
print('Confusion Matirx Decision Tree',confusion_matrix(y_pred=y_dt,y_true=y_test))

Accuracy Decision Tree 0.855072463768116
Classificaition Decision Tree
               precision    recall  f1-score   support

           0       0.89      0.77      0.83        31
           1       0.83      0.92      0.88        38

    accuracy                           0.86        69
   macro avg       0.86      0.85      0.85        69
weighted avg       0.86      0.86      0.85        69

Confusion Matirx Decision Tree [[24  7]
 [ 3 35]]


In [179]:
print('Accuracy Logistic Regression',accuracy_score(y_pred=y_lg,y_true=y_test))
print('Classificaition Logistic Regression\n',classification_report(y_pred=y_lg,y_true=y_test))
print('Confusion Matirx Logistic Regression\n',confusion_matrix(y_pred=y_lg,y_true=y_test))

Accuracy Logistic Regression 0.8840579710144928
Classificaition Logistic Regression
               precision    recall  f1-score   support

           0       0.96      0.77      0.86        31
           1       0.84      0.97      0.90        38

    accuracy                           0.88        69
   macro avg       0.90      0.87      0.88        69
weighted avg       0.89      0.88      0.88        69

Confusion Matirx Logistic Regression
 [[24  7]
 [ 1 37]]


In [176]:
print('Accuracy Naive Bayes',accuracy_score(y_pred=y_nb,y_true=y_test))
print('Classificaition Naive Bayes\n',classification_report(y_pred=y_nb,y_true=y_test))
print('Confusion Matirx Naive Bayes\n',confusion_matrix(y_pred=y_nb,y_true=y_test))

Accuracy Naive Bayes 0.7971014492753623
Classificaition Naive Bayes
               precision    recall  f1-score   support

           0       0.76      0.81      0.78        31
           1       0.83      0.79      0.81        38

    accuracy                           0.80        69
   macro avg       0.80      0.80      0.80        69
weighted avg       0.80      0.80      0.80        69

Confusion Matirx Naive Bayes
 [[25  6]
 [ 8 30]]


In [175]:
print('Accuracy KNN',accuracy_score(y_pred=y_knn,y_true=y_test))
print('Classificaition KNN\n',classification_report(y_pred=y_knn,y_true=y_test))
print('Confusion Matirx KNN\n',confusion_matrix(y_pred=y_knn,y_true=y_test))

Accuracy KNN 0.8985507246376812
Classificaition KNN
               precision    recall  f1-score   support

           0       0.90      0.87      0.89        31
           1       0.90      0.92      0.91        38

    accuracy                           0.90        69
   macro avg       0.90      0.90      0.90        69
weighted avg       0.90      0.90      0.90        69

Confusion Matirx KNN
 [[27  4]
 [ 3 35]]
