In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

c:\Users\crkpn\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\crkpn\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\crkpn\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df = pd.read_csv('./advertising.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [4]:
df.isna().sum()

Daily Time Spent on Site    0
Age                         0
Area Income                 0
Daily Internet Usage        0
Ad Topic Line               0
City                        0
Male                        0
Country                     0
Timestamp                   0
Clicked on Ad               0
dtype: int64

In [75]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier


In [6]:
for i in df.columns:
    print(i)
    print(df[i].unique())

Daily Time Spent on Site
[68.95 80.23 69.47 74.15 68.37 59.99 88.91 66.   74.53 69.88 47.64 83.07
 69.57 79.52 42.95 63.45 55.39 82.03 54.7  74.58 77.22 84.59 41.49 87.29
 41.39 78.74 48.53 51.95 70.2  76.02 67.64 86.41 59.05 55.6  57.64 84.37
 62.26 65.82 50.43 38.93 84.98 64.24 82.52 81.38 80.47 37.68 69.62 85.4
 44.33 48.01 73.18 79.94 33.33 50.33 62.31 80.6  65.19 44.98 77.63 41.82
 85.61 85.84 72.08 86.06 45.96 62.42 63.89 35.33 75.74 78.53 46.13 69.01
 55.35 33.21 38.46 64.1  49.81 82.73 56.14 55.13 78.11 73.46 56.64 68.94
 70.79 57.76 77.51 52.7  57.7  56.89 69.9  55.79 70.03 50.08 43.67 72.84
 45.72 39.94 35.61 79.71 63.6  89.91 68.18 66.49 80.49 72.23 42.39 47.53
 74.02 66.63 63.24 71.   69.   76.99 72.6  61.88 84.45 88.97 86.19 49.58
 77.65 37.75 62.33 79.57 80.31 89.05 70.41 67.36 46.98 41.67 51.24 75.7
 43.49 49.89 38.37 38.52 71.89 75.8  83.86 37.51 83.67 69.08 37.47 56.04
 70.92 49.78 68.61 58.18 78.54 37.   65.4  87.98 44.64 41.73 80.46 75.55
 76.32 82.68 72.01 75.83 41.

In [7]:
df.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

          Timestamp  Clicked on Ad  
0  27-03-2016 00:53              0  
1  04-04-2016 01:39              0  
2  13-03-2016 20:35              0  
3  10-01-2016 02:31              0  
4  03-06-2016 03:36              0

In [8]:
print(len(df['Ad Topic Line'].unique()),df.shape)
print(len(df['City'].unique()),df.shape)
print(len(df['Country'].unique()),df.shape)

1000 (1000, 10)
969 (1000, 10)
237 (1000, 10)


In [9]:
df['Timestamp']=pd.to_datetime(df['Timestamp'])

In [10]:
df.drop('Timestamp',axis=1,inplace=True)

In [11]:
enc = LabelEncoder()
scaler = StandardScaler()

In [12]:
df['Country'] = enc.fit_transform(df['Country'])
df['Ad Topic Line'] = enc.fit_transform(df['Ad Topic Line'])
df['City'] = enc.fit_transform(df['City'])

In [13]:
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

     Ad Topic Line  City  Male  Country  Clicked on Ad  
0               91   961     0      215              0  
1              464   903     1      147              0  
2              566   111     0      184              0  
3              903   939     1      103              0  
4              766   805     0       96              0  
..             ...   ...   ...      ...            ...  
995            345   126     1      116              1  
996            359   488     1       26              1  
997            263   798     1      140              1  
998            641   935     0       85              0  
999            971   744     0       28              1  

[1000 rows x 9 columns]

In [14]:
X = df.drop('Clicked on Ad',axis=1)
Y = df['Clicked on Ad']

In [15]:
scaled_x = scaler.fit_transform(X)

In [16]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [17]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [76]:
lr = LogisticRegression()
nb = GaussianNB()
knn = KNeighborsClassifier(n_neighbors=5)
dt = DecisionTreeClassifier()

In [77]:
lr.fit(x_train,y_train)
nb.fit(x_train,y_train)
knn.fit(x_train,y_train)
dt.fit(x_train,y_train)

c:\Users\crkpn\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [78]:
lr_pred = lr.predict(x_test)
nb_pred = nb.predict(x_test)
knn_pred = knn.predict(x_test)
dt_pred = dt.predict(x_test)

In [79]:
lr.fit(x_train_scaled,y_train)
nb.fit(x_train_scaled,y_train)
knn.fit(x_train_scaled,y_train)
dt.fit(x_train_scaled,y_train)

DecisionTreeClassifier()

In [80]:
lr_pred = lr.predict(x_test_scaled)
nb_pred = nb.predict(x_test_scaled)
knn_pred = knn.predict(x_test_scaled)
dt_pred = dt.predict(x_test_scaled)

In [39]:
results_df = pd.DataFrame({'prediction': lr_pred, 'test_label': y_test})
results_df # Display the first few rows


prediction  test_label
521           1           1
737           1           1
740           1           1
660           1           1
411           0           0
..          ...         ...
408           1           1
332           1           1
208           1           1
613           0           0
78            1           1

[200 rows x 2 columns]

In [40]:
results_df = pd.DataFrame({'prediction': nb_pred, 'test_label': y_test})
results_df # Display the first few rows


prediction  test_label
521           1           1
737           1           1
740           1           1
660           1           1
411           0           0
..          ...         ...
408           1           1
332           1           1
208           1           1
613           0           0
78            1           1

[200 rows x 2 columns]

In [55]:
results_df = pd.DataFrame({'prediction': knn_pred, 'test_label': y_test})
results_df # Display the first few rows


prediction  test_label
521           1           1
737           1           1
740           1           1
660           1           1
411           0           0
..          ...         ...
408           1           1
332           1           1
208           1           1
613           0           0
78            1           1

[200 rows x 2 columns]

In [81]:
results_df = pd.DataFrame({'prediction': dt_pred, 'test_label': y_test})
results_df # Display the first few rows


prediction  test_label
521           1           1
737           1           1
740           1           1
660           1           1
411           0           0
..          ...         ...
408           0           1
332           1           1
208           1           1
613           0           0
78            1           1

[200 rows x 2 columns]

In [71]:
# Logistic Regression
report = classification_report(y_test, lr_pred)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.98      0.93        89
           1       0.98      0.90      0.94       111

    accuracy                           0.94       200
   macro avg       0.93      0.94      0.93       200
weighted avg       0.94      0.94      0.94       200



In [67]:
# Naive Bayes
report = classification_report(y_test, nb_pred)
print(report)

              precision    recall  f1-score   support

           0       0.91      0.97      0.94        89
           1       0.97      0.93      0.95       111

    accuracy                           0.94       200
   macro avg       0.94      0.95      0.94       200
weighted avg       0.95      0.94      0.95       200



In [70]:
# KNN
report = classification_report(y_test, knn_pred)
print(report)

              precision    recall  f1-score   support

           0       0.87      1.00      0.93        89
           1       1.00      0.88      0.94       111

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.93       200
weighted avg       0.94      0.94      0.94       200



In [82]:
# Decision Tree
report = classification_report(y_test, dt_pred)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.90      0.91        89
           1       0.92      0.94      0.93       111

    accuracy                           0.92       200
   macro avg       0.92      0.92      0.92       200
weighted avg       0.92      0.92      0.92       200



In [72]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, lr_pred)
cm

array([[ 87,   2],
       [ 11, 100]], dtype=int64)

In [73]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, nb_pred)
cm

array([[ 86,   3],
       [  8, 103]], dtype=int64)

In [74]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, knn_pred)
cm

array([[89,  0],
       [13, 98]], dtype=int64)

In [83]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, dt_pred)
cm

array([[ 80,   9],
       [  7, 104]], dtype=int64)