In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('./Salary_Data.csv')

In [4]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
df.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [6]:
X = df['YearsExperience']
Y = df['Salary']

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2,random_state=100)

In [9]:
scaler = StandardScaler()

In [ ]:
X = scaler.fit_transform(X)
y = scaler.fit_transform(y)

In [10]:
x_train_scaled = scaler.fit_transform(x_train.values.reshape(-1,1))
x_test_scaled = scaler.fit_transform(x_test.values.reshape(-1,1))

In [11]:
y_train_scaled = scaler.fit_transform(y_train.values.reshape(-1,1))
y_test_scaled = scaler.fit_transform(y_test.values.reshape(-1,1))

In [12]:
x_train_scaled

array([[ 1.60848776],
       [ 1.38894062],
       [-0.80653083],
       [ 0.03506656],
       [ 0.98643752],
       [-0.44061892],
       [-1.09926036],
       [ 1.93780848],
       [-1.50176346],
       [-1.42858108],
       [ 0.2546137 ],
       [-0.25766297],
       [ 0.29120489],
       [ 0.69370799],
       [-1.35539869],
       [ 0.58393442],
       [-0.47721011],
       [-0.03811582],
       [-0.11129821],
       [ 1.09621109],
       [-0.73334845],
       [-1.17244274],
       [ 1.27916705],
       [-0.73334845]])

In [13]:
y_train_scaled

array([[ 1.41447337],
       [ 1.14556459],
       [-0.5866152 ],
       [ 0.28793886],
       [ 0.9823816 ],
       [-0.75269583],
       [-1.35902738],
       [ 1.76665124],
       [-1.3799209 ],
       [-1.11829434],
       [ 0.22217001],
       [-0.54997528],
       [ 0.70169161],
       [ 0.86689532],
       [-1.44138141],
       [ 0.61773625],
       [-0.46964197],
       [-0.36246735],
       [-0.28968316],
       [ 1.45934869],
       [-0.80412897],
       [-1.22047435],
       [ 1.29231489],
       [-0.42286031]])

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
model.fit(x_train_scaled,y_train)

LinearRegression()

In [17]:
y_pred = model.predict(x_test_scaled)

In [18]:
y_test

9      57189.0
26    116969.0
28    122391.0
13     57081.0
5      56642.0
12     56957.0
Name: Salary, dtype: float64

In [19]:
y_pred.reshape(-1,1)

array([[ 57869.17649163],
       [107853.00641775],
       [114747.32778687],
       [ 61316.33717619],
       [ 50974.85512251],
       [ 60454.54700505]])

In [20]:
results_df = pd.DataFrame({'prediction': y_pred, 'test_label': y_test})
results_df # Display the first few rows

prediction  test_label
9    57869.176492     57189.0
26  107853.006418    116969.0
28  114747.327787    122391.0
13   61316.337176     57081.0
5    50974.855123     56642.0
12   60454.547005     56957.0

In [21]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Mean Squared Error (MSE)
mse = mean_squared_error(y_pred, y_test)
print(f'Mean Squared Error (MSE): {mse}')

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print(f'Root Mean Squared Error (RMSE): {rmse}')

r2 = r2_score(y_test,y_pred)

Mean Squared Error (MSE): 34046191.84403626
Root Mean Squared Error (RMSE): 5834.911468397465


In [22]:
r2 = r2_score(y_test,y_pred)

In [23]:
r2

0.9611545799276339

In [24]:
from sklearn.preprocessing import PolynomialFeatures

In [25]:
poly = PolynomialFeatures(degree=5)

In [26]:
x_train_poly = poly.fit_transform(x_train_scaled)
x_test_poly = poly.fit_transform(x_test_scaled)

poly_model = LinearRegression()

In [27]:
poly_model.fit(x_train_poly,y_train_scaled)

LinearRegression()

In [28]:
y_pred_poly = poly_model.predict(x_test_poly)

In [29]:
results_df = pd.DataFrame({'prediction': y_pred_poly, 'test_label': y_test})
results_df # Display the first few rows

ValueError: Per-column arrays must each be 1-dimensional

In [30]:
poly_model.coef_

array([[ 0.        ,  1.32712648,  0.13332347, -0.3492896 , -0.06096576,
         0.07627718]])

In [31]:
poly_model.intercept_

array([-0.01410639])

In [32]:
# Mean Squared Error (MSE)
mse = mean_squared_error(y_test_scaled, y_pred_poly)
print(f'Mean Squared Error (MSE): {mse}')

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print(f'Root Mean Squared Error (RMSE): {rmse}')

r2 = r2_score(y_test_scaled, y_pred_poly)
print(r2)

Mean Squared Error (MSE): 0.015027268920825747
Root Mean Squared Error (RMSE): 0.12258576149302881
0.9849727310791743
